### ISSUE TITLE
Research and Select External API

### ISSUE THREAD

**Issue by nbenkl01** [nbenkl01/Sp24-CS-120_FinalProject#2]
Research and choose an external API to integrate in the app.

**Comment by CaseyMOwen** [comment]
Gets title, description, img link from a search on the title, but has slow response time (25s)
This could work, would just have to let the api run in  the background and tell the user something like "your book will be posted soon"
https://rapidapi.com/riyanshgupta750/api/getbooksinfo

Better, faster option: https://developers.google.com/books/docs/overview
